!function(t){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=t()
else if("function"==typeof define&&define.amd)define([],t)
else{var e
e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this,e.McHead=t()}}(function(){return function t(e,i,s){function n(r,a){if(!i[r]){if(!e[r]){var h="function"==typeof require&&require
if(!a&&h)return h(r,!0)
if(o)return o(r,!0)
var u=new Error("Cannot find module '"+r+"'")
throw u.code="MODULE_NOT_FOUND",u}var c=i[r]={exports:{}}
e[r][0].call(c.exports,function(t){var i=e[r][1][t]
return n(i?i:t)},c,c.exports,t,e,i,s)}return i[r].exports}for(var o="function"==typeof require&&require,r=0;r<s.length;r++)n(s[r])
return n}({1:[function(t,e,i){function s(t){var e=new Image
return e.onload=function(){var e=this.width,i=this.height
64!=e||64!=i&&32!=i?alert("Given image of size "+e+"px wide and "+i+"px high doesn't correspond with a Minecraft skin resoultion (64x32 or 64x64)!"):(t.model.setImage(this,e,i),t.justRender())},e}function n(t,e){var i=new FileReader,n=s(t)
i.onload=function(t){n.src=t.target.result},i.readAsDataURL(e)}var o=t("./dom"),r=t("./utils"),a=t("./camera"),h=t("./model"),u=t("./mouse"),c=document.createElement("canvas"),l=e.exports=function(t,e,i,s,n){this.options=t,this.canvas=e,this.output=i,this.size=r.point(s,n)}
l.prototype={init:function(){this.initThree(),this.initModel(),this.initMouseHandler(),this.initOptions()},initThree:function(){var t=this,e=this.size.x,i=this.size.y,s=new a(e,i,50,.1,1e3,(-1e3),1e3),n=new THREE.Scene,o=new THREE.TextureLoader,r=new THREE.WebGLRenderer({preserveDrawingBuffer:!0,alpha:!0})
r.setClearColor(16777215,0),r.setSize(e,i),r.domElement.className="renderer",this.canvas.appendChild(r.domElement),o.load("steve.png",function(e){t.model.setTexture(e),t.justRender()}),this.scene=n,this.renderer=r,this.camera=s},initMouseHandler:function(){this.mouse=new u(this,Math.PI/4,Math.PI/4),this.mouse.attach(this.renderer.domElement)},initModel:function(){this.model=new h,this.scene.add(this.model.group),this.model.headOnly(!0)},initOptions:function(){var t=this
o.$$("input",this.options).forEach(function(e){o.on(e,"change",function(){t.change(e.name,e)})}),o.on(o.$("#reset"),"click",function(){o.$("[name=x]").value=o.$("[name=y]").value=45,t.mouse.setX(45),t.mouse.setY(45),t.justRender()})},fromUsername:function(t){var e=new Image,i=this
e.onload=function(){var t=s(i)
c.width=this.width,c.height=this.height,c.getContext("2d").drawImage(this,0,0),t.src=c.toDataURL("image/png")},e.crossOrigin="Anonymous",e.src="https://skins.minecraft.net/MinecraftSkins/"+t+".png"},change:function(t,e){"head"==t?this.model.headOnly(e.checked):"outer"==t?this.model.includeHair(e.checked):"flat"==t?this.camera.toggle():"texture"==t?n(this,e.files[0]):"x"==t?this.mouse.setY(parseInt(e.value)):"y"==t?this.mouse.setX(parseInt(e.value)):"username"==t&&this.fromUsername(e.value),this.justRender()},changed:function(t,e){o.$("[name=x]").value=e.toFixed(4),o.$("[name=y]").value=t.toFixed(4)},up:function(){this.output.src=this.renderer.domElement.toDataURL("image/png")},render:function(t,e){this.model.rotate(t,e),this.renderer.render(this.scene,this.camera.camera)},justRender:function(){this.render(this.mouse.result.x,this.mouse.result.y),this.up()}}},{"./camera":2,"./dom":3,"./model":5,"./mouse":6,"./utils":7}],2:[function(t,e,i){var s=e.exports=function(t,e,i,s,n,o,r){this.fov=i
var a=t/2,h=e/2
this.ortho=new THREE.OrthographicCamera((-a),a,h,(-h),o,r),this.ortho.position.z=4,this.perspec=new THREE.PerspectiveCamera(i,t/e,s,n),this.perspec.position.z=544,this.toOrtho()}
s.prototype={toOrtho:function(){this.camera=this.ortho},toPerspec:function(){this.camera=this.perspec},toggle:function(){this.camera==this.ortho?this.toPerspec():this.toOrtho()}}},{}],3:[function(t,e,i){function s(t){return Array.prototype.slice.call(t)}function n(t,e){return(e||document).querySelector(t)}function o(t,e){return s((e||document).querySelectorAll(t))}function r(t,e,i){t.addEventListener(e,i)}e.exports={$:n,$$:o,on:r}},{}],4:[function(t,e,i){e.exports={App:t("./app"),dom:t("./dom"),version:"0.1.0"}},{"./app":1,"./dom":3}],5:[function(t,e,i){var s=t("./utils"),n=e.exports=function(){this.createMesh(),this.applyUV(64,32)}
n.prototype={createMesh:function(){var t=new THREE.MeshBasicMaterial,e=new THREE.MeshBasicMaterial({side:THREE.DoubleSide,transparent:!0}),i=s.limb(t,0,8,8,8,8),n=s.limb(e,0,8,8,8,8),o=s.limb(t,0,-2,8,12,4),r=s.limb(t,-6,-2,4,12,4),a=s.limb(t,6,-2,4,12,4),h=s.limb(t,-2,-14,4,12,4),u=s.limb(t,2,-14,4,12,4),c=new THREE.Object3D
s.invert(a),s.invert(u),c.position.set(0,32,0),c.scale.x=c.scale.y=c.scale.z=96,n.scale.x=n.scale.y=n.scale.z=1.1,c.add(i),c.add(n),c.add(o),c.add(r),c.add(a),c.add(h),c.add(u),this.material=t,this.outerMaterial=e,this.head=i,this.outer=n,this.body=o,this.left_arm=r,this.left_leg=h,this.right_arm=a,this.right_leg=u,this.group=c},rotate:function(t,e){this.group.rotation.x=e,this.group.rotation.y=t},headOnly:function(t){t?(this.group.remove(this.body),this.group.remove(this.left_arm),this.group.remove(this.left_leg),this.group.remove(this.right_arm),this.group.remove(this.right_leg),this.head.position.y=0,this.outer.position.y=0):(this.group.add(this.body),this.group.add(this.left_arm),this.group.add(this.left_leg),this.group.add(this.right_arm),this.group.add(this.right_leg),this.head.position.y=1,this.outer.position.y=1)},includeHair:function(t){this.outer.visible=t},applyUV:function(t,e){var i=32==e?0:32
s.apply_cube(t,e,this.head.geometry,0,i+16,8,8,8),s.apply_cube(t,e,this.outer.geometry,32,i+16,8,8,8),s.apply_cube(t,e,this.body.geometry,16,i+0,8,12,4),s.apply_cube(t,e,this.left_arm.geometry,40,i+0,4,12,4),s.apply_cube(t,e,this.right_arm.geometry,40,i+0,4,12,4),s.apply_cube(t,e,this.left_leg.geometry,0,i+0,4,12,4),s.apply_cube(t,e,this.right_leg.geometry,0,i+0,4,12,4)},setTexture:function(t){t.minFilter=t.magFilter=THREE.NearestFilter,this.material.map=t,this.material.map.needsUpdate=!0,this.outerMaterial.map=t,this.outerMaterial.map.needsUpdate=!0},setImage:function(t,e,i){var s=this.group.parent,n=null==this.body.parent
s.remove(this.group),this.createMesh(),this.applyUV(e,i),s.add(this.group),this.setTexture(new THREE.Texture(t)),this.headOnly(n)}}},{"./utils":7}],6:[function(t,e,i){var s=t("./dom"),n=t("./utils"),o=e.exports=function(t,e,i){this.target=t,this.on=!1,this.result=n.point(e,i),this.first=n.point(0,0),this.tmp=n.point(0,0),this.last=n.point(0,0)}
o.prototype={attach:function(t){s.on(t,"mousedown",this.down.bind(this)),s.on(t,"mousemove",this.move.bind(this)),s.on(t,"mouseout",this.out.bind(this)),s.on(t,"mouseup",this.up.bind(this))},out:function(){this.on=!1},down:function(t){this.on=!0,this.first.x=t.pageX,this.first.y=t.pageY,this.last.x=this.result.x,this.last.y=this.result.y},move:function(t){this.on&&(this.tmp.x=t.pageX-this.first.x,this.tmp.y=t.pageY-this.first.y,this.applyRotation(),this.render())},up:function(t){this.on=!1,this.applyRotation(),this.target.up()},applyRotation:function(){var t=2*Math.PI
this.result.x=(this.last.x+this.tmp.x/90)%t,this.result.y=(this.last.y+this.tmp.y/90)%t,this.target.changed(this.getX(),this.getY())},setX:function(t){this.result.x=t/180*Math.PI,this.render()},setY:function(t){this.result.y=t/180*Math.PI,this.render()},getX:function(){return 180*this.result.x/Math.PI},getY:function(){return 180*this.result.y/Math.PI},render:function(){this.target.render(this.result.x,this.result.y)}}},{"./dom":3,"./utils":7}],7:[function(t,e,i){function s(t,e){return{x:t,y:e}}function n(t,e,i,s){return new THREE.Vector2(t/i,e/s)}function o(t,e,i,s,o,r,a,h){s=2*s
var u=[n(o,r+h,t,e),n(o+a,r+h,t,e),n(o+a,r,t,e),n(o,r,t,e)]
6!=s?(i.faceVertexUvs[0][s]=[u[0],u[3],u[1]],i.faceVertexUvs[0][s+1]=[u[3],u[2],u[1]]):(i.faceVertexUvs[0][s]=[u[3],u[0],u[2]],i.faceVertexUvs[0][s+1]=[u[0],u[1],u[2]])}function r(t,e,i,s,n,r,a,h){o(t,e,i,4,s+h,n,r,a),o(t,e,i,5,s+h+r+h,n,r,a),o(t,e,i,0,s+h+r,n,h,a),o(t,e,i,1,s,n,h,a),o(t,e,i,2,s+h,n+a,r,h),o(t,e,i,3,s+h+r,n+a,r,h),i.uvsNeedUpdate=!0}function a(t,e,i,s,n,o){var r=new THREE.BoxGeometry(s/8,n/8,o/8),a=new THREE.Mesh(r,t)
return a.position.x=e?e/8:0,a.position.y=i?i/8:0,a}function h(t){var e=t.geometry
e.scale(-1,1,1),e.scale(-1,1,1),e.dynamic=!0,e.__dirtyVertices=!0,e.__dirtyNormals=!0,t.flipSided=!0
for(var i=0,s=e.faces.length;i<s;i++){var n=e.faces[i]
n.normal.x*=-1,n.normal.y*=-1,n.normal.z*=-1}e.computeVertexNormals(),e.computeFaceNormals()}e.exports={point:s,vec:n,apply_uv:o,apply_cube:r,limb:a,invert:h}},{}]},{},[4])(4)})
