!function(t){if("object"==typeof exports&&"undefined"!=typeof module)module.exports=t()
else if("function"==typeof define&&define.amd)define([],t)
else{var e
e="undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this,e.McHead=t()}}(function(){return function t(e,i,n){function s(r,a){if(!i[r]){if(!e[r]){var h="function"==typeof require&&require
if(!a&&h)return h(r,!0)
if(o)return o(r,!0)
var u=new Error("Cannot find module '"+r+"'")
throw u.code="MODULE_NOT_FOUND",u}var l=i[r]={exports:{}}
e[r][0].call(l.exports,function(t){var i=e[r][1][t]
return s(i?i:t)},l,l.exports,t,e,i,n)}return i[r].exports}for(var o="function"==typeof require&&require,r=0;r<n.length;r++)s(n[r])
return s}({1:[function(t,e,i){function n(t,e){var i=new XMLHttpRequest
i.responseType="blob",i.onload=function(){var t=new FileReader
t.onloadend=function(){e(t.result)},t.readAsDataURL(i.response)},i.open("GET",t),i.send()}function s(t){var e=new Image
return e.onload=function(){var e=this.width,i=this.height
64!=e||64!=i&&32!=i?alert("Given image of size "+e+"px wide and "+i+"px high doesn't correspond with a Minecraft skin resoultion (64x32 or 64x64)!"):(t.model.setImage(this,e,i),t.justRender())},e}function o(t,e){var i=new FileReader,n=s(t)
i.onload=function(t){n.src=t.target.result},i.readAsDataURL(e)}var r=t("./dom"),a=t("./utils"),h=t("./camera"),u=t("./model"),l=t("./mouse"),c=(document.createElement("canvas"),e.exports=function(t,e,i,n,s){this.options=t,this.canvas=e,this.output=i,this.size=a.point(n,s)})
c.prototype={init:function(){this.initThree(),this.initModel(),this.initMouseHandler(),this.initOptions()},initThree:function(){var t=this,e=this.size.x,i=this.size.y,n=new h(e,i,50,.1,1e3,(-1e3),1e3),s=new THREE.Scene,o=new THREE.TextureLoader,r=new THREE.WebGLRenderer({preserveDrawingBuffer:!0,alpha:!0})
r.setClearColor(16777215,0),r.setSize(e,i),r.domElement.className="renderer",this.canvas.appendChild(r.domElement),o.load("steve.png",function(e){t.model.setTexture(e),t.justRender()}),this.scene=s,this.renderer=r,this.camera=n},initMouseHandler:function(){this.mouse=new l(this,Math.PI/4,Math.PI/4),this.mouse.attach(this.renderer.domElement)},initModel:function(){this.model=new u,this.scene.add(this.model.group),this.model.headOnly(!0)},initOptions:function(){var t=this
r.$$("input",this.options).forEach(function(e){r.on(e,"change",function(){t.change(e.name,e)})}),r.on(r.$("#reset"),"click",function(){r.$("[name=x]").value=r.$("[name=y]").value=45,t.mouse.setX(45),t.mouse.setY(45),t.justRender()})},fromUsername:function(t){var e="https://skins.minecraft.net/MinecraftSkins/"+t+".png",i=this
n(e,function(t){var e=s(i)
e.src=t})},change:function(t,e){"head"==t?this.model.headOnly(e.checked):"outer"==t?this.model.includeHair(e.checked):"flat"==t?this.camera.toggle():"texture"==t?o(this,e.files[0]):"x"==t?this.mouse.setY(parseInt(e.value)):"y"==t?this.mouse.setX(parseInt(e.value)):"username"==t&&this.fromUsername(e.value),this.justRender()},changed:function(t,e){r.$("[name=x]").value=e.toFixed(4),r.$("[name=y]").value=t.toFixed(4)},up:function(){this.output.src=this.renderer.domElement.toDataURL("image/png")},render:function(t,e){this.model.rotate(t,e),this.renderer.render(this.scene,this.camera.camera)},justRender:function(){this.render(this.mouse.result.x,this.mouse.result.y),this.up()}}},{"./camera":2,"./dom":3,"./model":5,"./mouse":6,"./utils":7}],2:[function(t,e,i){var n=e.exports=function(t,e,i,n,s,o,r){this.fov=i
var a=t/2,h=e/2
this.ortho=new THREE.OrthographicCamera((-a),a,h,(-h),o,r),this.ortho.position.z=4,this.perspec=new THREE.PerspectiveCamera(i,t/e,n,s),this.perspec.position.z=544,this.toOrtho()}
n.prototype={toOrtho:function(){this.camera=this.ortho},toPerspec:function(){this.camera=this.perspec},toggle:function(){this.camera==this.ortho?this.toPerspec():this.toOrtho()}}},{}],3:[function(t,e,i){function n(t){return Array.prototype.slice.call(t)}function s(t,e){return(e||document).querySelector(t)}function o(t,e){return n((e||document).querySelectorAll(t))}function r(t,e,i){t.addEventListener(e,i)}e.exports={$:s,$$:o,on:r}},{}],4:[function(t,e,i){e.exports={App:t("./app"),dom:t("./dom"),version:"0.1.0"}},{"./app":1,"./dom":3}],5:[function(t,e,i){var n=t("./utils"),s=e.exports=function(){this.createMesh(),this.applyUV(64,32)}
s.prototype={createMesh:function(){var t=new THREE.MeshBasicMaterial,e=new THREE.MeshBasicMaterial({side:THREE.DoubleSide,transparent:!0}),i=n.limb(t,0,8,8,8,8),s=n.limb(e,0,8,8,8,8),o=n.limb(t,0,-2,8,12,4),r=n.limb(t,-6,-2,4,12,4),a=n.limb(t,6,-2,4,12,4),h=n.limb(t,-2,-14,4,12,4),u=n.limb(t,2,-14,4,12,4),l=new THREE.Object3D
n.invert(a),n.invert(u),l.position.set(0,32,0),l.scale.x=l.scale.y=l.scale.z=96,s.scale.x=s.scale.y=s.scale.z=1.1,l.add(i),l.add(s),l.add(o),l.add(r),l.add(a),l.add(h),l.add(u),this.material=t,this.outerMaterial=e,this.head=i,this.outer=s,this.body=o,this.left_arm=r,this.left_leg=h,this.right_arm=a,this.right_leg=u,this.group=l},rotate:function(t,e){this.group.rotation.x=e,this.group.rotation.y=t},headOnly:function(t){t?(this.group.remove(this.body),this.group.remove(this.left_arm),this.group.remove(this.left_leg),this.group.remove(this.right_arm),this.group.remove(this.right_leg),this.head.position.y=0,this.outer.position.y=0):(this.group.add(this.body),this.group.add(this.left_arm),this.group.add(this.left_leg),this.group.add(this.right_arm),this.group.add(this.right_leg),this.head.position.y=1,this.outer.position.y=1)},includeHair:function(t){this.outer.visible=t},applyUV:function(t,e){var i=32==e?0:32
n.apply_cube(t,e,this.head.geometry,0,i+16,8,8,8),n.apply_cube(t,e,this.outer.geometry,32,i+16,8,8,8),n.apply_cube(t,e,this.body.geometry,16,i+0,8,12,4),n.apply_cube(t,e,this.left_arm.geometry,40,i+0,4,12,4),n.apply_cube(t,e,this.right_arm.geometry,40,i+0,4,12,4),n.apply_cube(t,e,this.left_leg.geometry,0,i+0,4,12,4),n.apply_cube(t,e,this.right_leg.geometry,0,i+0,4,12,4)},setTexture:function(t){t.minFilter=t.magFilter=THREE.NearestFilter,this.material.map=t,this.material.map.needsUpdate=!0,this.outerMaterial.map=t,this.outerMaterial.map.needsUpdate=!0},setImage:function(t,e,i){var n=this.group.parent,s=null==this.body.parent
n.remove(this.group),this.createMesh(),this.applyUV(e,i),n.add(this.group),this.setTexture(new THREE.Texture(t)),this.headOnly(s)}}},{"./utils":7}],6:[function(t,e,i){var n=t("./dom"),s=t("./utils"),o=e.exports=function(t,e,i){this.target=t,this.on=!1,this.result=s.point(e,i),this.first=s.point(0,0),this.tmp=s.point(0,0),this.last=s.point(0,0)}
o.prototype={attach:function(t){n.on(t,"mousedown",this.down.bind(this)),n.on(t,"mousemove",this.move.bind(this)),n.on(t,"mouseout",this.out.bind(this)),n.on(t,"mouseup",this.up.bind(this))},out:function(){this.on=!1},down:function(t){this.on=!0,this.first.x=t.pageX,this.first.y=t.pageY,this.last.x=this.result.x,this.last.y=this.result.y},move:function(t){this.on&&(this.tmp.x=t.pageX-this.first.x,this.tmp.y=t.pageY-this.first.y,this.applyRotation(),this.render())},up:function(t){this.on=!1,this.applyRotation(),this.target.up()},applyRotation:function(){var t=2*Math.PI
this.result.x=(this.last.x+this.tmp.x/90)%t,this.result.y=(this.last.y+this.tmp.y/90)%t,this.target.changed(this.getX(),this.getY())},setX:function(t){this.result.x=t/180*Math.PI,this.render()},setY:function(t){this.result.y=t/180*Math.PI,this.render()},getX:function(){return 180*this.result.x/Math.PI},getY:function(){return 180*this.result.y/Math.PI},render:function(){this.target.render(this.result.x,this.result.y)}}},{"./dom":3,"./utils":7}],7:[function(t,e,i){function n(t,e){return{x:t,y:e}}function s(t,e,i,n){return new THREE.Vector2(t/i,e/n)}function o(t,e,i,n,o,r,a,h){n=2*n
var u=[s(o,r+h,t,e),s(o+a,r+h,t,e),s(o+a,r,t,e),s(o,r,t,e)]
6!=n?(i.faceVertexUvs[0][n]=[u[0],u[3],u[1]],i.faceVertexUvs[0][n+1]=[u[3],u[2],u[1]]):(i.faceVertexUvs[0][n]=[u[3],u[0],u[2]],i.faceVertexUvs[0][n+1]=[u[0],u[1],u[2]])}function r(t,e,i,n,s,r,a,h){o(t,e,i,4,n+h,s,r,a),o(t,e,i,5,n+h+r+h,s,r,a),o(t,e,i,0,n+h+r,s,h,a),o(t,e,i,1,n,s,h,a),o(t,e,i,2,n+h,s+a,r,h),o(t,e,i,3,n+h+r,s+a,r,h),i.uvsNeedUpdate=!0}function a(t,e,i,n,s,o){var r=new THREE.BoxGeometry(n/8,s/8,o/8),a=new THREE.Mesh(r,t)
return a.position.x=e?e/8:0,a.position.y=i?i/8:0,a}function h(t){var e=t.geometry
e.scale(-1,1,1),e.scale(-1,1,1),e.dynamic=!0,e.__dirtyVertices=!0,e.__dirtyNormals=!0,t.flipSided=!0
for(var i=0,n=e.faces.length;i<n;i++){var s=e.faces[i]
s.normal.x*=-1,s.normal.y*=-1,s.normal.z*=-1}e.computeVertexNormals(),e.computeFaceNormals()}e.exports={point:n,vec:s,apply_uv:o,apply_cube:r,limb:a,invert:h}},{}]},{},[4])(4)})
